# docker-compose build && docker-compose up -d
version: "3.3"
services: 
  apidb:
    container_name: data_manager_db
    restart: unless-stopped
    build:
        context: ..
        dockerfile: docker/postgres/Dockerfile
    environment:        
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PW}
  api:
    container_name: data_manager_api
    restart: unless-stopped
    build:
        context: ..
        dockerfile: docker/api/Dockerfile
    environment:
        POSTGRES_URL: "apidb:5432"
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PW: ${POSTGRES_PW}
        POSTGRES_DB: ${POSTGRES_DB}
        TBRD_REPO_DB_USER: ${TBRD_REPO_DB_USER}
        TBRD_REPO_DB_PASS: ${TBRD_REPO_DB_PASS}
        KUBERNETES_API_PORT: ${KUBERNETES_API_PORT}
        KUBERNETES_API_HOST: ${KUBERNETES_API_HOST}
    depends_on:
        - apidb
    links:
        - apidb
    ports:
        - "8090:8090"
