# docker-compose build && docker-compose up -d
version: "3"
services: 
  apidb:
    container_name: terrabrasilisrd_db
    restart: unless-stopped
    build:
        context: ..
        dockerfile: docker/postgres/Dockerfile
    environment:        
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PW}
  api:
    container_name: terrabrasilisrd_api
    restart: unless-stopped
    build:
        context: ..
        dockerfile: docker/api/Dockerfile
    environment:
        POSTGRES_URL: "apidb:5431"
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PW: ${POSTGRES_PW}
        POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
        - apidb
    links:
        - apidb
    ports:
        - "8090:8090"
