version: "3.3"
services: 

  tbrd_data-manager-db:
    restart: unless-stopped
    container_name: tbrd_data-manager-db    
    build:
        context: ..
        dockerfile: docker/postgres/Dockerfile
    env_file:
        - app-variables.env
    networks: 
        - tbrd_network

  tbrd_data-manager-api:
    container_name: tbrd_data-manager-api
    restart: unless-stopped
    build:
        context: ..
        dockerfile: docker/api/Dockerfile
    environment:
        POSTGRES_URL: "apidb:5432"
    depends_on:
        - apidb
    links:
        - apidb
    ports:
        - "5000:5000"
    env_file:
        - app-variables.env
    networks: 
        - tbrd_network

networks: 
    tbrd_network:
        external: true
