# docker-compose build && docker-compose up -d
version: "3.3"
services: 
  apidb:
    restart: unless-stopped
    container_name: terrabrasilisrd_db    
    build:
        context: ..
        dockerfile: docker/postgres/Dockerfile
    env_file:
        - app-variables.env       
  api:
    container_name: terrabrasilisrd_api
    restart: unless-stopped
    build:
        context: ..
        dockerfile: docker/api/Dockerfile
    environment:
        POSTGRES_URL: "apidb:5432"
    depends_on:
        - apidb
    links:
        - apidb
    ports:
        - "8090:8090"
    env_file:
        - app-variables.env    


